rules:
  # noEmptyOperationIDs: true
  noUnusedDefinitions: true
  noDuplicateOperationIDs: true
  # noEmptyDescriptions:
  #   operations: true
  #   parameters: true
  #   properties: false
  naming:
    # tags: PascalCase
    # definitions: PascalCase
    properties: CamelCase
    # parameters: SnakeCase
    # paths: KebabCase
