site_name: OpenAPI Linter
site_author: James Batt
repo_name: GitHub
repo_url: https://github.com/place1/openapi-linter
docs_dir: ./pages
edit_uri: edit/master/docs/pages/

theme:
  name: material
  include_sidebar: true
  palette:
    primary: cyan
    accent: cyan
  feature:
    tabs: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - Getting Started: index.md
